# Generated by Django 5.2 on 2025-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Country ID')),
                ('country_name', models.CharField(max_length=255, unique=True, verbose_name='Country Name')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('film_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Film ID')),
                ('title', models.CharField(max_length=255, verbose_name='Film Title')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='Release Year')),
                ('runtime', models.IntegerField(blank=True, null=True, verbose_name='Runtime (in minutes)')),
                ('synopsis', models.TextField(blank=True, null=True, verbose_name='Synopsis')),
                ('budget', models.BigIntegerField(blank=True, null=True, verbose_name='Budget')),
                ('revenue', models.BigIntegerField(blank=True, null=True, verbose_name='Revenue')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Film Status')),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tagline')),
                ('awards_and_nominations', models.CharField(blank=True, max_length=255, null=True, verbose_name='Awards and Nominations')),
                ('poster_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poster URL')),
                ('backdrop_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Backdrop URL')),
                ('popularity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Popularity Score')),
                ('api_film_id', models.IntegerField(verbose_name='TMDb Film ID')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
                'db_table': 'films',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmAndCountry',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film-Country Relationship',
                'verbose_name_plural': 'Film-Country Relationships',
                'db_table': 'filmsandcountries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmAndGenre',
            fields=[
                ('film_genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Film-Genre Relationship',
                'verbose_name_plural': 'Film-Genre Relationships',
                'db_table': 'filmsandgenres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmAndLanguage',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_language', models.BooleanField(default=False, verbose_name='Is Original Language?')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film-Language Relationship',
                'verbose_name_plural': 'Film-Language Relationships',
                'db_table': 'filmsandlanguages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmAndProductionCompany',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Record ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film and Production Company',
                'verbose_name_plural': 'Films and Production Companies',
                'db_table': 'filmsandproductioncompanies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmRole',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Role ID')),
                ('name', models.CharField(max_length=255, verbose_name='Role Name')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film Role',
                'verbose_name_plural': 'Film Roles',
                'db_table': 'filmsroles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilmsAndPersons',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Record ID')),
                ('character', models.CharField(blank=True, max_length=255, null=True, verbose_name='Character')),
                ('display_order', models.IntegerField(blank=True, null=True, verbose_name='Display Order')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film and Person Record',
                'verbose_name_plural': 'Film and Person Records',
                'db_table': 'filmsandpersons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Genre ID')),
                ('genre_name', models.CharField(max_length=80, unique=True, verbose_name='Genre Name')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=255, unique=True, verbose_name='Language Name')),
                ('iso_639_1', models.CharField(max_length=10, unique=True, verbose_name='ISO 639-1 Code')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Person ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Birth')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('deathday', models.DateField(blank=True, null=True, verbose_name='Deathday')),
                ('picture_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Picture URL')),
                ('alias', models.CharField(blank=True, max_length=255, null=True, verbose_name='Alias')),
                ('api_person_id', models.IntegerField(verbose_name='TMDb Person ID')),
                ('last_synced', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'persons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Company ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('origin_country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origin Country')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Production Company',
                'verbose_name_plural': 'Production Companies',
                'db_table': 'productioncompanies',
                'managed': False,
            },
        ),
    ]
