# Generated by Django 5.2 on 2025-04-29 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmAndUser',
            fields=[
                ('film_and_user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Film and User ID')),
                ('watched', models.BooleanField(default=True, verbose_name='Watched?')),
                ('liked', models.BooleanField(default=False, verbose_name='Liked?')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Film and User Relationship',
                'verbose_name_plural': 'Film and User Relationships',
                'db_table': 'filmsAndUsers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False, verbose_name='List ID')),
                ('list_name', models.CharField(max_length=100, verbose_name='List Name')),
                ('list_description', models.TextField(blank=True, null=True, verbose_name='List Description')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'db_table': 'lists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListAndFilm',
            fields=[
                ('list_film_id', models.AutoField(primary_key=True, serialize=False, verbose_name='List Film ID')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Sort Order')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'List-Film Relationship',
                'verbose_name_plural': 'List-Film Relationships',
                'db_table': 'listsandfilms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListAndLikeByUser',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Like ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'List Like by User',
                'verbose_name_plural': 'List Likes by Users',
                'db_table': 'listsandlikesbyusers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Entry ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'db_table': 'watchlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='tabla_ejemplo',
            fields=[
                ('campo', models.AutoField(primary_key=True, serialize=False, verbose_name='Like ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Follower ID')),
                ('date_followed', models.DateTimeField(verbose_name='Date Followed')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='followers_followed_set', to=settings.AUTH_USER_MODEL, verbose_name='Followed User')),
                ('follower_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Follower User')),
            ],
        ),
    ]
