film_titles = [
    "The Dark Knight",
    "Django Unchained",
    "La La Land",
    "Donnie Darko",
    "Fight Club",
    "Casablanca",
    "Lost in Translation",
    "The Godfather",
    "Oldboy",
    "Metropolis",
    "Chinatown",
    "Pulp Fiction",
    "Taxi Driver",
    "Whiplash",
    "Her",
    "The Big Lebowski",
    "Monty Python and the Holy Grail",
    "Hellraiser",
    "Alien: Romulus",
    "The Good, the Bad and the Ugly",
    "Come and See",
    "The Empire Strikes Back",
    "Attack of the Killer Tomatoes!",
    "12 Angry Men",
    "Spirited Away",
    "Pan's Labyrinth",
    "City of God",
    "The Shawshank Redemption",
    "Amélie",
    "Life Is Beautiful",
    "Requiem for a Dream",
    "Se7en",
    "Eternal Sunshine of the Spotless Mind",
    "Trainspotting",
    "The Pianist",
    "The Departed",
    "American Beauty",
    "No Country for Old Men",
    "The Silence of the Lambs",
    "There Will Be Blood",
    "Memento",
    "Goodfellas",
    "The Matrix",
    "Parasite",
    "Birdman",
    "A Clockwork Orange",
    "Interstellar",
    "Inception",
    "Arrival",
    "Grave of the Fireflies"
]