MOCK_USER_START_ID = 6
MOCK_USER_COUNT = 30
MOCK_USER_IDS = list(range(MOCK_USER_START_ID, MOCK_USER_START_ID + MOCK_USER_COUNT))

FILMS_PER_USER = 20
FOLLOWERS_PER_USER = 8
LISTS_PER_USER = 3
LIST_FILMS_MIN = 2
LIST_FILMS_MAX = 8
LIKES_PER_LIST_MAX = 10
WATCHLIST_PER_USER = 15

RATINGS_COUNT = 10
FILMS_PER_USER_LOG = 8
REVIEWS_PERCENTAGE = 0.6
LIKES_PER_REVIEW_MAX = 3