# Generated by Django 5.2 on 2025-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Log ID')),
                ('liked', models.BooleanField(default=False, verbose_name='Liked?')),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry Date')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_value', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Rating Value')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Review ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewAndLikeByUser',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Like ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Review and Like by User',
                'verbose_name_plural': 'Reviews and Likes by Users',
                'db_table': 'reviewsandlikesbyuser',
                'managed': False,
            },
        ),
    ]
