# Generated by Django 5.2 on 2025-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Comment ID')),
                ('body', models.TextField(verbose_name='Comment Body')),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommentAndLikeByUser',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Like ID')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Comment and Like by User',
                'verbose_name_plural': 'Comments and Likes by Users',
                'db_table': 'commentsandlikesbyuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateConversation',
            fields=[
                ('conversation_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Conversation ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject')),
                ('date_created', models.DateTimeField(verbose_name='Date Created')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Private Conversation',
                'verbose_name_plural': 'Private Conversations',
                'db_table': 'privateconversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Message ID')),
                ('content', models.TextField(verbose_name='Message Content')),
                ('date_sent', models.DateTimeField(verbose_name='Date Sent')),
                ('read_status', models.BooleanField(default=False, verbose_name='Read Status')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active?')),
                ('deleted', models.BooleanField(default=False, verbose_name='Is Deleted?')),
            ],
            options={
                'verbose_name': 'Private Message',
                'verbose_name_plural': 'Private Messages',
                'db_table': 'privatemessages',
                'managed': False,
            },
        ),
    ]
